Algoritmo "Concatenação"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Autor(a)    : Lorena Queiroz
// Data atual  : 11/05/2022
Var
// Seção de Declarações das variáveis 
  nome: caractere
  numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("Digite o nome: ")
  leia(nome)
  escreval("Digite o número: ")
  leia(numero)
  
  escreval(nome, " : ", numero, 15)
  
  
Fimalgoritmo