Algoritmo "Entrada e saída de dados"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Autor(a)    : Lorena Queiroz
// Data atual  : 11/05/2022
Var
// Seção de Declarações das variáveis 
  nome: caractere
  idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval("Digite seu nome:")
  leia(nome)
  escreval("Digite sua idade")
  leia(idade)

  escreval("O nome digitado foi: ", nome)
  escreval("A idade digitada foi: ", idade)

Fimalgoritmo