Algoritmo "Operadores Relacionais"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Autor(a)    : Lorena Queiroz
// Data atual  : 11/05/2022
Var
// Seção de Declarações das variáveis 
  nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  nota01 := 10
  nota02 := 15
  
  se(nota01 <> nota02) entao
      escreval("Nota02 é diferente")
  senao
      escreval("Nota01 é igual")
  fimse

Fimalgoritmo